### ISSUE TITLE
Highlight without filter

### ISSUE THREAD

**Issue by sQVe** [folke/paint.nvim#1]
👋🏼,

I want to use this plugin as a way for me to highlight certain patterns for **all** buffers. This seems to be a bit tricky as `filter` is   required. I've tried using:

```lua
{
  filter = function()
    return true
  end,
  pattern = 'NOTE',
  hl = '@text.note',
},
```

and:

```lua
{
  filter = {},
  pattern = 'NOTE',
  hl = '@text.note',
},
```

Sadly neither of these work.

What's the best way to apply an highlight for all buffers? 🙏

**Comment by folke** [comment]
Should be fixed now. Either config option should work as expected.
