### ISSUE TITLE
remove the default configuration

### ISSUE THREAD

**Issue by XXiaoA** [folke/paint.nvim#4]
Remove https://github.com/folke/paint.nvim/blob/7ce3e100b192384ce283640b8e5d7144b3b5913c/lua/paint/config.lua#L18-L25. nvim nightly semantic token will highlight the `@something` in comments now

**Comment by TheSafdarAwan** [comment]
what is the solution for this

**Comment by folke** [comment]
Just set `config.highlights = {}`
