### ISSUE TITLE
feature: Paint comments only

### ISSUE THREAD

**Issue by aloknigam247** [folke/paint.nvim#8]
### Did you check the docs?

- [X] I have read all the paint.nvim docs

### Is your feature request related to a problem? Please describe.

Paint changes highlight everywhere.
Instead it should work for comments only.

### Describe the solution you'd like

Apply highlights only in comments.

### Describe alternatives you've considered

Nothing

### Additional context

```lua
    opts = {
        highlights = {
            {
                filter = { filetype = 'python' },
                pattern = '%a+: ',
                hl = 'Constant'
            }
        }
    }
```
I used above config to highight the param names in python docstring. But it chnaged highlight in other parts too.

![image](https://github.com/folke/paint.nvim/assets/45559588/783a33e5-c729-4db5-9fd6-599c878a7f10)

**Comment by folke** [comment]
This is not the goal of paint. Paint is to highlight patterns anywhere.

An alternative plugin is https://github.com/echasnovski/mini.hipatterns
